openapi: 3.0.3
info:
  title: Health Tracker API
  description: Spring Boot API for Android health tracking application
  version: 1.0.0
  contact:
    name: API Support
    email: support@healthtracker.com

servers:
  - url: http://localhost:8081
    description: Local development server
  - url: https://api.healthtracker.com
    description: Production server

security:
  - bearerAuth: [ ]

paths:
  /auth/token:
    post:
      tags:
        - Authentication
      summary: Generate OAuth 2.0 access token
      description: Authenticate device and generate access token for API access
      security: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRequest'
            examples:
              deviceAuth:
                summary: Device authentication request
                value:
                  deviceId: "android-device-12345"
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
              examples:
                successfulAuth:
                  summary: Successful authentication response
                  value:
                    accessToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                    expiresIn: 3600
        '400':
          description: Bad request - invalid device ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /health/data/daily:
    post:
      tags:
        - Health Data
      summary: Submit health tracking data
      description: Submit daily health metrics including steps, active minutes, and calories burned
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DailyReportRequest'
            examples:
              dailyHealthData:
                summary: Daily health metrics submission
                value:
                  date: "2024-03-15"
                  steps: 8542
                  stand: 10
                  distance: 100
                  activeMinutes: 67
                  activeCalories: 300.5
                  totalCalories: 1500.5
                  basalMetabolicRate: 900.5
                  averageHeartRate: 60
                  averageRestingHeartRate: 45
                  timeZone: "-0500"
      responses:
        '200':
          description: Health data submitted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
              examples:
                dataSubmitted:
                  summary: Successful data submission
                  value:
                    message: "Health data submitted successfully"
        '400':
          description: Bad request - invalid data format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - invalid or expired token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Unprocessable entity - validation errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: OAuth 2.0 Bearer token authentication

  schemas:
    TokenRequest:
      type: object
      required:
        - deviceId
      properties:
        deviceId:
          type: string
          description: Unique identifier for the requesting device
          example: "android-device-12345"
          minLength: 1
          maxLength: 255

    TokenResponse:
      type: object
      required:
        - accessToken
        - expiresIn
      properties:
        accessToken:
          type: string
          description: OAuth 2.0 access token
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        expiresIn:
          type: integer
          format: int64
          description: Token expiration time in seconds
          example: 3600

    DailyReportRequest:
      type: object
      required:
        - date
        - steps
        - distance
        - stand
        - activeMinutes
        - activeCalories
        - totalCalories
        - basalMetabolicRate
        - averageHeartRate
        - averageRestingHeartRate
        - timeZone
      properties:
        date:
          type: string
          format: date
          description: Date in ISO 8601 format (YYYY-MM-DD)
          example: "2024-03-15"
        steps:
          type: integer
          description: Total number of steps taken
          minimum: 0
          example: 8542
        stand:
          type: integer
          description: Total stand hours
          minimum: 0
          example: 10
        distance:
          type: number
          format: double
          description: Total distance taken (meters)
          minimum: 0
          example: 2180.5
        activeMinutes:
          type: integer
          description: Total active minutes
          minimum: 0
          example: 67
        activeCalories:
          type: number
          format: double
          description: Total active calories burned (kilocalorie)
          minimum: 0
          example: 2180.5
        totalCalories:
          type: number
          format: double
          description: Total daily calories burned (kilocalorie)
          minimum: 0
          example: 3000.5
        basalMetabolicRate:
          type: number
          format: double
          description: Basal metabolic rate (kilocalorie)
          minimum: 0
          example: 1000.5
        averageHeartRate:
          type: integer
          description: Average Heart Rate
          minimum: 0
          example: 67
        averageRestingHeartRate:
          type: integer
          description: Average Heart Rate
          minimum: 0
          example: 67
        timeZone:
          type: string
          description: Timezone Offset value
          example: "-0500"

    SuccessResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Success message
          example: "Health data submitted successfully"

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
          example: "INVALID_REQUEST"
        message:
          type: string
          description: Human-readable error message
          example: "Invalid device ID provided"
        timestamp:
          type: string
          format: date-time
          description: Error timestamp
          example: "2024-03-15T10:30:00Z"