/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.15.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.pennyquin.openapi.api;

import com.pennyquin.openapi.model.DailyReportRequest;
import com.pennyquin.openapi.model.ErrorResponse;
import com.pennyquin.openapi.model.SuccessResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.lang.Nullable;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-09-01T14:09:06.896297600+02:00[Europe/Berlin]", comments = "Generator version: 7.15.0")
@Validated
@Tag(name = "Health Data", description = "the Health Data API")
public interface HealthApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    public static final String PATH_HEALTH_DATA_DAILY_POST = "/health/data/daily";
    /**
     * POST /health/data/daily : Submit health tracking data
     * Submit daily health metrics including steps, active minutes, and calories burned
     *
     * @param dailyReportRequest  (required)
     * @return Health data submitted successfully (status code 200)
     *         or Bad request - invalid data format (status code 400)
     *         or Unauthorized - invalid or expired token (status code 401)
     *         or Unprocessable entity - validation errors (status code 422)
     */
    @Operation(
        operationId = "healthDataDailyPost",
        summary = "Submit health tracking data",
        description = "Submit daily health metrics including steps, active minutes, and calories burned",
        tags = { "Health Data" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Health data submitted successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SuccessResponse.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"message\":\"Health data submitted successfully\"}"
                    )
                })

            }),
            @ApiResponse(responseCode = "400", description = "Bad request - invalid data format", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized - invalid or expired token", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "422", description = "Unprocessable entity - validation errors", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = HealthApi.PATH_HEALTH_DATA_DAILY_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<SuccessResponse> healthDataDailyPost(
        @Parameter(name = "DailyReportRequest", description = "", required = true) @Valid @RequestBody DailyReportRequest dailyReportRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"message\" : \"Health data submitted successfully\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"INVALID_REQUEST\", \"message\" : \"Invalid device ID provided\", \"timestamp\" : \"2024-03-15T10:30:00Z\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"INVALID_REQUEST\", \"message\" : \"Invalid device ID provided\", \"timestamp\" : \"2024-03-15T10:30:00Z\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"INVALID_REQUEST\", \"message\" : \"Invalid device ID provided\", \"timestamp\" : \"2024-03-15T10:30:00Z\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
